# Introduction to Vectors and Matrices
* Test1
    - Test2
        - Test2
    - Test2

##Data Set Information:
We have chosen the ‘Seeds Data Set’ from the UCI repository.
The examined group comprised kernels belonging to three different varieties of wheat: 
####Kama 
####Rosa 
####Canadian 

70 elements each, randomly selected for the experiment. 
High quality visualization of the internal kernel structure was detected using a soft X-ray technique. It is non-destructive and considerably cheaper than other more sophisticated imaging techniques like scanning microscopy or laser technology. The images were recorded on 13x18 cm X-ray KODAK plates. Studies were conducted using combine harvested wheat grain originating from experimental fields, explored at the Institute of Agrophysics of the Polish Academy of Sciences in Lublin. 


## Basics of NumPy Array Object

In [3]:
x = np.array ([[1,2,3], [4,5,6]])

x

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
print('We just create a', type(x))

We just create a <class 'numpy.ndarray'>


In [10]:
print("Our template has shape as", x.shape)

Our template has shape as (2, 3)


In [11]:
print("Total size is", x.size)

Total size is 6


In [14]:
print('The dimension of our array', x.ndim)

The dimension of our array 2


In [16]:
print('Data type pf elements', x.dtype)

Data type pf elements int32


In [17]:
print('It consumes', x.nbytes, "bytes")

It consumes 24 bytes


In [21]:
x = np.array ([[1,2,3], [4,5,5]], dtype = np.float)
print(x)
print(x.nbytes)

[[1. 2. 3.]
 [4. 5. 5.]]
48


In [22]:
x = np.array ([[1,2,3], [4,5,5]], dtype = np.complex)
print(x)
print(x.nbytes)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 5.+0.j]]
96


In [23]:
Data_Cancer = np.random.rand(10000, 100)

In [24]:
Data_Cancer

array([[0.19757388, 0.43331182, 0.58638056, ..., 0.81300667, 0.89022304,
        0.51073461],
       [0.39189605, 0.02434803, 0.67722055, ..., 0.73192468, 0.33800248,
        0.13294563],
       [0.43952069, 0.5277462 , 0.6771495 , ..., 0.74832237, 0.08962401,
        0.60644254],
       ...,
       [0.56178702, 0.10799436, 0.12860986, ..., 0.72524781, 0.04477582,
        0.5992766 ],
       [0.12503099, 0.183922  , 0.24509107, ..., 0.23769484, 0.12804011,
        0.32623468],
       [0.7519785 , 0.20833183, 0.64577715, ..., 0.8066291 , 0.82466246,
        0.1910504 ]])

In [25]:
my_list = [2,14,6,8]
my_list + 2

TypeError: can only concatenate list (not "int") to list

In [26]:
my_array = np.array(my_list)

In [27]:
type(my_array)

numpy.ndarray

In [28]:
my_array + 2

array([ 4, 16,  8, 10])

In [48]:
my_array - 1

array([ 1, 13,  5,  7])

In [29]:
my_array ** 2

array([  4, 196,  36,  64], dtype=int32)

In [30]:
my_array / 2

array([1., 7., 3., 4.])

In [32]:
my_array / 7

array([0.28571429, 2.        , 0.85714286, 1.14285714])

In [37]:
second_array = np.zeros(4)

In [35]:
print(second_array)

[0. 0. 0. 0.]


In [42]:
second_array = np.zeros((4,5))

In [43]:
print(second_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [44]:
second_array = np.zeros(4) + 3

In [46]:
second_array

array([3., 3., 3., 3.])

In [47]:
second_array / my_array

array([1.5       , 0.21428571, 0.5       , 0.375     ])

In [49]:
second_array = np.identity(4)

In [50]:
print(second_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [53]:
second_array = np.identity(4) + 3

second_array

array([[4., 3., 3., 3.],
       [3., 4., 3., 3.],
       [3., 3., 4., 3.],
       [3., 3., 3., 4.]])

## Working with Multidimensional Arrays

In [54]:
c = np.ones((4,4))

In [55]:
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [56]:
c.dot(c)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [9]:
## TEST